[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = {version = "4.9.0", features = ["experimental-io-uring"]}
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
